-- Phase 1.4.2: lineage column on bookings so we can attribute a booking to the
-- recurring reservation rule that materialised it. Lets us cap by max_occurrences
-- and supports "cancel and pause this series" UX in a later phase.

ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS class_recurring_reservation_id uuid
  REFERENCES public.class_recurring_reservations(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_bookings_class_recurring
  ON public.bookings (class_recurring_reservation_id)
  WHERE class_recurring_reservation_id IS NOT NULL;

COMMENT ON COLUMN public.bookings.class_recurring_reservation_id IS
  'When set, this booking was generated by the named class_recurring_reservations rule.';
