-- The column registry (Docs/collective-one-venue-plan.md §6.3, Appendix F; W3a).
--
-- THE HOLE. Copying a collective service into a member venue read the origin row with
-- select('*') and copied every column except a short denylist
-- (service-duplication.ts SERVICE_COLUMNS_NOT_COPIED). So any column added to services later is
-- copied from one independent business into another without anyone deciding it should be, and
-- today the host's online meeting link, joining information and add-on costs already travel.
--
-- THE FIX. Every column of the nine tables a collective copies is classified once, here:
--   host        written from the master on every copy and, later, every engine apply
--   venue       seeded from the master when a copy is created, then the venue's own
--   identity    ids and parent pointers, mapped or recomputed, never copied as they are
--   derived     computed from more than one source (for today's plain copy, taken as it is)
--   not_copied  never written from another venue
-- The copy code reads this table and copies only host, venue and derived columns, so a column
-- nobody has classified is not copied. supabase/tests/collective_column_classes_test.sql fails
-- when any column of these tables is unclassified.
--
-- Service role only: nothing client-facing reads it.

CREATE TABLE IF NOT EXISTS public.collective_column_classes (
  table_name   text NOT NULL,
  column_name  text NOT NULL,
  class        text NOT NULL,
  note         text,
  PRIMARY KEY (table_name, column_name),
  CONSTRAINT collective_column_classes_class_valid
    CHECK (class IN ('host', 'identity', 'venue', 'not_copied', 'derived'))
);

ALTER TABLE public.collective_column_classes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.collective_column_classes FROM PUBLIC, anon, authenticated;

INSERT INTO public.collective_column_classes (table_name, column_name, class, note) VALUES
  ('service_items', 'id', 'identity', NULL),
  ('service_items', 'venue_id', 'identity', NULL),
  ('service_items', 'category_id', 'identity', NULL),
  ('service_items', 'name', 'host', 'D29: one name everywhere'),
  ('service_items', 'description', 'host', NULL),
  ('service_items', 'item_type', 'host', NULL),
  ('service_items', 'duration_minutes', 'host', NULL),
  ('service_items', 'buffer_minutes', 'host', NULL),
  ('service_items', 'processing_time_minutes', 'host', NULL),
  ('service_items', 'price_pence', 'host', NULL),
  ('service_items', 'deposit_pence', 'host', NULL),
  ('service_items', 'price_type', 'host', NULL),
  ('service_items', 'colour', 'host', NULL),
  ('service_items', 'is_bookable_online', 'host', NULL),
  ('service_items', 'staff_may_customize_name', 'host', NULL),
  ('service_items', 'staff_may_customize_description', 'host', NULL),
  ('service_items', 'staff_may_customize_duration', 'host', NULL),
  ('service_items', 'staff_may_customize_buffer', 'host', NULL),
  ('service_items', 'staff_may_customize_price', 'host', NULL),
  ('service_items', 'staff_may_customize_deposit', 'host', NULL),
  ('service_items', 'staff_may_customize_colour', 'host', NULL),
  ('service_items', 'custom_availability_enabled', 'host', NULL),
  ('service_items', 'custom_working_hours', 'host', NULL),
  ('service_items', 'payment_requirement', 'host', NULL),
  ('service_items', 'max_advance_booking_days', 'host', NULL),
  ('service_items', 'min_booking_notice_hours', 'host', NULL),
  ('service_items', 'cancellation_notice_hours', 'host', NULL),
  ('service_items', 'allow_same_day_booking', 'host', NULL),
  ('service_items', 'processing_time_blocks', 'host', NULL),
  ('service_items', 'location_type', 'host', NULL),
  ('service_items', 'booking_interval_minutes', 'host', NULL),
  ('service_items', 'booking_minute_marks', 'host', NULL),
  ('service_items', 'booking_start_times', 'host', NULL),
  ('service_items', 'capacity_per_session', 'venue', 'D40: seeded from the master once, never overwritten'),
  ('service_items', 'pre_appointment_instructions', 'venue', 'D53: seeded from the master; describes the venue the guest visits'),
  ('service_items', 'sort_order', 'venue', 'the members own list order; the page follows the masters'),
  ('service_items', 'is_active', 'derived', 'master active AND offering active'),
  ('service_items', 'online_meeting_url', 'not_copied', 'D11: each venue sets its own; a host link would send a members guests to the hosts meeting room'),
  ('service_items', 'online_meeting_info', 'not_copied', 'D11: each venue sets its own'),
  ('service_items', 'created_by_staff_id', 'not_copied', NULL),
  ('service_items', 'created_at', 'not_copied', NULL),
  ('service_items', 'updated_at', 'not_copied', NULL),
  ('service_items', 'synced_from_service_id', 'not_copied', NULL),
  ('service_items', 'sync_state', 'not_copied', NULL),
  ('service_items', 'synced_at', 'not_copied', NULL),
  ('service_variants', 'id', 'identity', NULL),
  ('service_variants', 'venue_id', 'identity', NULL),
  ('service_variants', 'service_item_id', 'identity', NULL),
  ('service_variants', 'appointment_service_id', 'not_copied', NULL),
  ('service_variants', 'name', 'host', NULL),
  ('service_variants', 'description', 'host', NULL),
  ('service_variants', 'duration_minutes', 'host', NULL),
  ('service_variants', 'buffer_minutes', 'host', NULL),
  ('service_variants', 'price_pence', 'host', NULL),
  ('service_variants', 'deposit_pence', 'host', NULL),
  ('service_variants', 'processing_time_blocks', 'host', NULL),
  ('service_variants', 'sort_order', 'host', NULL),
  ('service_variants', 'is_active', 'derived', NULL),
  ('service_variants', 'created_at', 'not_copied', NULL),
  ('service_variants', 'updated_at', 'not_copied', NULL),
  ('addon_groups', 'id', 'identity', NULL),
  ('addon_groups', 'venue_id', 'identity', NULL),
  ('addon_groups', 'name', 'host', NULL),
  ('addon_groups', 'prompt_to_client', 'host', NULL),
  ('addon_groups', 'description', 'host', NULL),
  ('addon_groups', 'selection_type', 'host', NULL),
  ('addon_groups', 'min_select', 'host', NULL),
  ('addon_groups', 'max_select', 'host', NULL),
  ('addon_groups', 'hidden_from_online', 'host', NULL),
  ('addon_groups', 'is_active', 'host', NULL),
  ('addon_groups', 'sort_order', 'venue', NULL),
  ('addon_groups', 'created_at', 'not_copied', NULL),
  ('addon_groups', 'updated_at', 'not_copied', NULL),
  ('addons', 'id', 'identity', NULL),
  ('addons', 'venue_id', 'identity', NULL),
  ('addons', 'addon_group_id', 'identity', NULL),
  ('addons', 'name', 'host', NULL),
  ('addons', 'description', 'host', NULL),
  ('addons', 'additional_price_pence', 'host', NULL),
  ('addons', 'additional_duration_minutes', 'host', NULL),
  ('addons', 'is_active', 'host', NULL),
  ('addons', 'sort_order', 'host', NULL),
  ('addons', 'cost_to_business_pence', 'not_copied', 'the hosts internal cost stays at the host'),
  ('addons', 'archived_at', 'derived', NULL),
  ('addons', 'created_at', 'not_copied', NULL),
  ('addons', 'updated_at', 'not_copied', NULL),
  ('service_addon_groups', 'id', 'identity', NULL),
  ('service_addon_groups', 'venue_id', 'identity', NULL),
  ('service_addon_groups', 'service_item_id', 'identity', NULL),
  ('service_addon_groups', 'addon_group_id', 'identity', NULL),
  ('service_addon_groups', 'appointment_service_id', 'not_copied', NULL),
  ('service_addon_groups', 'sort_order', 'host', NULL),
  ('service_addon_groups', 'created_at', 'not_copied', NULL),
  ('service_categories', 'id', 'identity', NULL),
  ('service_categories', 'venue_id', 'identity', NULL),
  ('service_categories', 'name', 'host', NULL),
  ('service_categories', 'sort_order', 'venue', NULL),
  ('service_categories', 'created_at', 'not_copied', NULL),
  ('service_categories', 'updated_at', 'not_copied', NULL),
  ('compliance_types', 'id', 'identity', NULL),
  ('compliance_types', 'venue_id', 'identity', NULL),
  ('compliance_types', 'current_version_id', 'identity', NULL),
  ('compliance_types', 'slug', 'derived', NULL),
  ('compliance_types', 'name', 'host', NULL),
  ('compliance_types', 'category', 'host', NULL),
  ('compliance_types', 'description', 'host', NULL),
  ('compliance_types', 'result_type', 'host', NULL),
  ('compliance_types', 'validity_period_days', 'host', NULL),
  ('compliance_types', 'capture_methods', 'host', NULL),
  ('compliance_types', 'form_link_expiry_days', 'host', NULL),
  ('compliance_types', 'library_template_slug', 'host', NULL),
  ('compliance_types', 'online_unmet_message', 'host', NULL),
  ('compliance_types', 'is_active', 'derived', NULL),
  ('compliance_types', 'archived_at', 'derived', NULL),
  ('compliance_types', 'created_at', 'not_copied', NULL),
  ('compliance_types', 'updated_at', 'not_copied', NULL),
  ('compliance_type_versions', 'id', 'identity', NULL),
  ('compliance_type_versions', 'venue_id', 'identity', NULL),
  ('compliance_type_versions', 'compliance_type_id', 'identity', NULL),
  ('compliance_type_versions', 'version_number', 'derived', NULL),
  ('compliance_type_versions', 'form_schema', 'host', NULL),
  ('compliance_type_versions', 'changelog', 'host', NULL),
  ('compliance_type_versions', 'created_by_staff_id', 'not_copied', NULL),
  ('compliance_type_versions', 'created_at', 'not_copied', NULL),
  ('service_compliance_requirements', 'id', 'identity', NULL),
  ('service_compliance_requirements', 'venue_id', 'identity', NULL),
  ('service_compliance_requirements', 'service_item_id', 'identity', NULL),
  ('service_compliance_requirements', 'compliance_type_id', 'identity', NULL),
  ('service_compliance_requirements', 'appointment_service_id', 'not_copied', NULL),
  ('service_compliance_requirements', 'enforcement', 'derived', NULL),
  ('service_compliance_requirements', 'lock_period_hours', 'derived', NULL),
  ('service_compliance_requirements', 'online_collection', 'derived', NULL),
  ('service_compliance_requirements', 'scope', 'derived', NULL),
  ('service_compliance_requirements', 'created_at', 'not_copied', NULL),
  ('service_compliance_requirements', 'updated_at', 'not_copied', NULL)
ON CONFLICT (table_name, column_name) DO UPDATE SET class = EXCLUDED.class, note = EXCLUDED.note;
